class CustomException(ValueError):
    """Raised when there is a problem during the onboarding process."""

    pass
